name: emulate
description: Emulate unsupported operating systems using QEMU.
inputs:
  operating-system:
    description: The operating-system specifier.
    required: true
runs:
  using: composite
  steps:
  - name: Boot guest ${{ inputs.operating-system }}.
    shell: bash
    working-directory: ${{ runner.temp }}
    env:
      EMULATE_OPERATING_SYSTEM: ${{ inputs.operating-system }}
    run: |
      if [ "$EMULATE_OPERATING_SYSTEM" = openbsd-release ]; then
        EMULATE_OPERATING_SYSTEM=openbsd-7.3 ;;
      fi

      export VAGRANT_HOME="$(mktemp --directory)"
      export VAGRANT_CWD="$GITHUB_ACTION_PATH/$EMULATE_OPERATING_SYSTEM"
      EMULATE_BASH_HIJACKER="$(mktemp)"
      cat > "$EMULATE_BASH_HIJACKER" << EOF
        RUN_SCRIPT="\$(ps -p \$$ -o args= | xargs -n 1 | tail -n 1)"
        VAGRANT_HOME="$VAGRANT_HOME" VAGRANT_CWD="$VAGRANT_CWD" exec vagrant ssh -c 'exec \$SHELL -se' < "\$RUN_SCRIPT"
      EOF

      echo "BASH_ENV=$EMULATE_BASH_HIJACKER" >> "$GITHUB_ENV"
      vagrant up
