Vagrant.configure("2") do |config|
  config.vm.guest = "openbsd"

  config.vm.box = "emulate/openbsd-7.2"
  config.vm.ignore_box_vagrantfile = true
  config.vm.box_check_update = false
  config.vm.box_download_checksum_type = "sha256"
  config.vm.box_download_checksum = "4344289d514194ee7b00a1719420f4fc02fff558a53f3229c640d6a6e5c19b64"
  config.vm.box_url = [
    "https://app.vagrantup.com/generic/boxes/openbsd7/versions/4.2.14/providers/virtualbox.box"
  ]

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |virtualbox|
    virtualbox.cpus = 2
    virtualbox.memory = 12 * 1024
    virtualbox.check_guest_additions = false
  end

  config.ssh.username = "root"
  config.ssh.insert_key = false
  config.ssh.sudo_command = "doas %c"
  config.ssh.shell = "ksh -l"
end
