Vagrant.configure("2") do |config|
  config.vm.guest = "openbsd"

  config.vm.box = "emulate/openbsd-current"
  config.vm.ignore_box_vagrantfile = true
  config.vm.box_check_update = false
  config.vm.box_download_checksum_type = "sha256"
  config.vm.box_download_checksum = "XXX"
  config.vm.box_url = [
    "https://app.vagrantup.com/mbuhl/boxes/OpenBSD/versions/0.0.0/providers/virtualbox.box"
  ]

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |virtualbox|
    virtualbox.cpus = 2
    virtualbox.memory = 12 * 1024
    virtualbox.check_guest_additions = false
  end

  config.ssh.username = "root"
  config.ssh.insert_key = false
  config.ssh.sudo_command = "doas %c"
  config.ssh.shell = "ksh -l"
end
