on:
  release:
    types: [ created ]

name: Handle Release
jobs:
  setup-hashicorp:
    runs-on: macos-12
    strategy:
      matrix:
        os: [ openbsd-current, openbsd-7.3, openbsd-7.2 ]
    steps:
    - name: Install Hashicorp Packer
      run: |
        brew tap hashicorp/tap
        brew install hashicorp/tap/packer
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Build
      run: |
        packer build "${{ matrix.os }}"
    - name: Checksum
      run: |
        sed -i -e "s/config.vm.box_download_checksum .*/config.vm.box_download_checksum = \"$(shasum -a 256 "${{ matrix.os }}/packer_default_virtualbox.box")\"/" "${{ matrix.os }}/Vagrantfile
    - name: Push tag and checksums
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add .
        git commit -m 'Update artifacts and checksums.'
        git tag -f latest
        git push --force origin latest
    - name: Upload
      run: |
        curl \
          -sSL \
          -XPOST \
          -H "Authorization: token ${GITHUB_TOKEN}" \
          --upload-file "${{ matrix.os }}/packer_default_virtualbox.box" \
          --header "Content-Type:application/octet-stream" \
          --write-out "%{errormsg}" \
          "https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/latest/assets?name=${{ matrix.os }}.box"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
