on:
  release:
    types: [ created ]

name: Handle Release
jobs:
  setup-hashicorp:
    runs-on: macos-12
    steps:
    - name: Install Hashicorp Packer
      run: |
        brew tap hashicorp/tap
        brew install hashicorp/tap/packer
    - name: Checkout repository
      uses: actions/checkout@master
    - name: Build
      run: |
        for p in openbsd-current openbsd-7.3 openbsd-7.2; do \
          for i in 1 2 3; do \
            packer build "$p" && break; \
            sleep 1;
          done \
        done
    - name: Checksum
      run: |
        for p in openbsd-current openbsd-7.3 openbsd-7.2; do \
          sed -i -e "s/config.vm.box_download_checksum .*/config.vm.box_download_checksum = \"$(shasum -a 256 "$p/packer_default_virtualbox.box")\"/" "$p/Vagrantfile; \
        done
    - name: Push tag and checksums
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add .
        git commit -m 'Update artifacts and checksums.'
        git tag -f latest
        git push --force origin latest
    - name: Upload
      run: |
        for p in openbsd-current openbsd-7.3 openbsd-7.2; do \
          curl \
            -sSL \
            -XPOST \
            -H "Authorization: token ${GITHUB_TOKEN}" \
            --upload-file "$p/packer_default_virtualbox.box" \
            --header "Content-Type:application/octet-stream" \
            --write-out "%{errormsg}" \
            "https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/latest/assets?name=$p.box"; \
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
